const DATA = {
  airlines: [
    {name:'Qatar Airways',country:'Qatar',iata:'QR',icao:'QTR',callsign:'QATARI',hub:'Doha',alliance:'oneworld',d:'easy'},
    {name:'Qantas',country:'Australia',iata:'QF',icao:'QFA',callsign:'QANTAS',hub:'Sydney',alliance:'oneworld',d:'easy'},
    {name:'Virgin Australia',country:'Australia',iata:'VA',icao:'VOZ',callsign:'VELOCITY',hub:'Brisbane',alliance:'None',d:'easy'},
    {name:'Jetstar',country:'Australia',iata:'JQ',icao:'JST',callsign:'JETSTAR',hub:'Melbourne',alliance:'None',d:'easy'},
    {name:'Air New Zealand',country:'New Zealand',iata:'NZ',icao:'ANZ',callsign:'NEW ZEALAND',hub:'Auckland',alliance:'Star Alliance',d:'easy'},
    {name:'Emirates',country:'United Arab Emirates',iata:'EK',icao:'UAE',callsign:'EMIRATES',hub:'Dubai',alliance:'None',d:'easy'},
    {name:'Etihad Airways',country:'United Arab Emirates',iata:'EY',icao:'ETD',callsign:'ETIHAD',hub:'Abu Dhabi',alliance:'None',d:'easy'},
    {name:'Singapore Airlines',country:'Singapore',iata:'SQ',icao:'SIA',callsign:'SINGAPORE',hub:'Singapore',alliance:'Star Alliance',d:'easy'},
    {name:'British Airways',country:'United Kingdom',iata:'BA',icao:'BAW',callsign:'SPEEDBIRD',hub:'London Heathrow',alliance:'oneworld',d:'easy'},
    {name:'American Airlines',country:'United States',iata:'AA',icao:'AAL',callsign:'AMERICAN',hub:'Dallas/Fort Worth',alliance:'oneworld',d:'easy'},
    {name:'United Airlines',country:'United States',iata:'UA',icao:'UAL',callsign:'UNITED',hub:'Chicago O’Hare',alliance:'Star Alliance',d:'easy'},
    {name:'Delta Air Lines',country:'United States',iata:'DL',icao:'DAL',callsign:'DELTA',hub:'Atlanta',alliance:'SkyTeam',d:'easy'},
    {name:'Lufthansa',country:'Germany',iata:'LH',icao:'DLH',callsign:'LUFTHANSA',hub:'Frankfurt',alliance:'Star Alliance',d:'easy'},
    {name:'Air France',country:'France',iata:'AF',icao:'AFR',callsign:'AIRFRANS',hub:'Paris Charles de Gaulle',alliance:'SkyTeam',d:'easy'},
    {name:'KLM',country:'Netherlands',iata:'KL',icao:'KLM',callsign:'KLM',hub:'Amsterdam',alliance:'SkyTeam',d:'easy'},
    {name:'Korean Air',country:'South Korea',iata:'KE',icao:'KAL',callsign:'KOREAN AIR',hub:'Seoul Incheon',alliance:'SkyTeam',d:'medium'},
    {name:'Cathay Pacific',country:'Hong Kong',iata:'CX',icao:'CPA',callsign:'CATHAY',hub:'Hong Kong',alliance:'oneworld',d:'medium'},
    {name:'Japan Airlines',country:'Japan',iata:'JL',icao:'JAL',callsign:'JAPAN AIR',hub:'Tokyo Haneda',alliance:'oneworld',d:'medium'},
    {name:'All Nippon Airways',country:'Japan',iata:'NH',icao:'ANA',callsign:'ALL NIPPON',hub:'Tokyo Haneda',alliance:'Star Alliance',d:'medium'},
    {name:'Malaysia Airlines',country:'Malaysia',iata:'MH',icao:'MAS',callsign:'MALAYSIAN',hub:'Kuala Lumpur',alliance:'oneworld',d:'medium'},
    {name:'Thai Airways',country:'Thailand',iata:'TG',icao:'THA',callsign:'THAI',hub:'Bangkok Suvarnabhumi',alliance:'Star Alliance',d:'medium'},
    {name:'Turkish Airlines',country:'Türkiye',iata:'TK',icao:'THY',callsign:'TURKISH',hub:'Istanbul',alliance:'Star Alliance',d:'medium'},
    {name:'Finnair',country:'Finland',iata:'AY',icao:'FIN',callsign:'FINNAIR',hub:'Helsinki',alliance:'oneworld',d:'medium'},
    {name:'Iberia',country:'Spain',iata:'IB',icao:'IBE',callsign:'IBERIA',hub:'Madrid',alliance:'oneworld',d:'medium'},
    {name:'EVA Air',country:'Taiwan',iata:'BR',icao:'EVA',callsign:'EVA',hub:'Taipei Taoyuan',alliance:'Star Alliance',d:'medium'},
    {name:'China Airlines',country:'Taiwan',iata:'CI',icao:'CAL',callsign:'DYNASTY',hub:'Taipei Taoyuan',alliance:'SkyTeam',d:'medium'},
    {name:'Fiji Airways',country:'Fiji',iata:'FJ',icao:'FJI',callsign:'FIJI',hub:'Nadi',alliance:'oneworld',d:'medium'},
    {name:'Air India',country:'India',iata:'AI',icao:'AIC',callsign:'AIR INDIA',hub:'Delhi',alliance:'Star Alliance',d:'medium'},
    {name:'Royal Jordanian',country:'Jordan',iata:'RJ',icao:'RJA',callsign:'JORDANIAN',hub:'Amman',alliance:'oneworld',d:'hard'},
    {name:'Royal Air Maroc',country:'Morocco',iata:'AT',icao:'RAM',callsign:'ROYALAIR MAROC',hub:'Casablanca',alliance:'oneworld',d:'hard'},
    {name:'Oman Air',country:'Oman',iata:'WY',icao:'OMA',callsign:'OMAN AIR',hub:'Muscat',alliance:'oneworld',d:'hard'},
    {name:'SriLankan Airlines',country:'Sri Lanka',iata:'UL',icao:'ALK',callsign:'SRILANKAN',hub:'Colombo',alliance:'oneworld',d:'hard'},
    {name:'Air Niugini',country:'Papua New Guinea',iata:'PX',icao:'ANG',callsign:'NIUGINI',hub:'Port Moresby',alliance:'None',d:'hard'},
    {name:'Aircalin',country:'New Caledonia',iata:'SB',icao:'ACI',callsign:'AIRCALIN',hub:'Nouméa',alliance:'None',d:'hard'},
    {name:'Air Tahiti Nui',country:'French Polynesia',iata:'TN',icao:'THT',callsign:'TAHITI AIRLINES',hub:'Papeete',alliance:'None',d:'hard'},
    {name:'RwandAir',country:'Rwanda',iata:'WB',icao:'RWD',callsign:'RWANDAIR',hub:'Kigali',alliance:'None',d:'hard'},
    {name:'Kenya Airways',country:'Kenya',iata:'KQ',icao:'KQA',callsign:'KENYA',hub:'Nairobi',alliance:'SkyTeam',d:'hard'},
    {name:'Air Astana',country:'Kazakhstan',iata:'KC',icao:'KZR',callsign:'ASTANALINE',hub:'Almaty',alliance:'None',d:'hard'}
  ],
  aircraft: [
    {name:'Boeing 777-300ER',maker:'Boeing',code:'B77W',engines:2,type:'wide-body jet',clue:'A long-range twinjet with raked wingtips and very large GE90 engines.',d:'easy'},
    {name:'Airbus A380-800',maker:'Airbus',code:'A388',engines:4,type:'double-deck wide-body jet',clue:'The only full-length double-deck passenger airliner in regular airline service.',d:'easy'},
    {name:'Boeing 787-9',maker:'Boeing',code:'B789',engines:2,type:'wide-body jet',clue:'A Dreamliner variant with swept wings and distinctive engine chevrons.',d:'easy'},
    {name:'Airbus A350-900',maker:'Airbus',code:'A359',engines:2,type:'wide-body jet',clue:'A composite Airbus twinjet with curved winglets and a black cockpit-mask appearance.',d:'easy'},
    {name:'Boeing 737-800',maker:'Boeing',code:'B738',engines:2,type:'narrow-body jet',clue:'A widely used Next Generation 737 variant, longer than the 737-700.',d:'easy'},
    {name:'Airbus A320neo',maker:'Airbus',code:'A20N',engines:2,type:'narrow-body jet',clue:'The re-engined member of the A320 family, often fitted with sharklets.',d:'easy'},
    {name:'Airbus A330-300',maker:'Airbus',code:'A333',engines:2,type:'wide-body jet',clue:'The longer passenger variant of the original A330 family.',d:'medium'},
    {name:'Boeing 747-8',maker:'Boeing',code:'B748',engines:4,type:'wide-body jet',clue:'The final and longest production version of the 747 family.',d:'medium'},
    {name:'Embraer E190',maker:'Embraer',code:'E190',engines:2,type:'regional jet',clue:'A Brazilian twinjet commonly arranged four seats across.',d:'medium'},
    {name:'ATR 72-600',maker:'ATR',code:'AT76',engines:2,type:'turboprop',clue:'A high-wing regional turboprop with six-bladed propellers on many examples.',d:'medium'},
    {name:'Airbus A220-300',maker:'Airbus',code:'BCS3',engines:2,type:'narrow-body jet',clue:'Originally developed as the Bombardier CSeries CS300.',d:'medium'},
    {name:'Boeing 767-300',maker:'Boeing',code:'B763',engines:2,type:'wide-body jet',clue:'A twin-aisle Boeing design introduced before the 777.',d:'medium'},
    {name:'Airbus A321neo',maker:'Airbus',code:'A21N',engines:2,type:'narrow-body jet',clue:'The longest common member of the re-engined A320neo family.',d:'medium'},
    {name:'Boeing 777-200LR',maker:'Boeing',code:'B77L',engines:2,type:'wide-body jet',clue:'The ultra-long-range shorter-fuselage passenger member of the 777 family.',d:'hard'},
    {name:'Airbus A350-1000',maker:'Airbus',code:'A35K',engines:2,type:'wide-body jet',clue:'The stretched A350 variant whose ICAO designator ends in K.',d:'hard'},
    {name:'De Havilland Dash 8 Q400',maker:'De Havilland Canada',code:'DH8D',engines:2,type:'turboprop',clue:'A fast high-wing regional turboprop with a T-tail.',d:'hard'},
    {name:'Fokker 100',maker:'Fokker',code:'F100',engines:2,type:'regional jet',clue:'A Dutch regional jet with rear-mounted engines and a T-tail.',d:'hard'},
    {name:'Antonov An-124',maker:'Antonov',code:'A124',engines:4,type:'heavy cargo jet',clue:'A very large Ukrainian-designed strategic airlifter with a nose cargo door.',d:'hard'},
    {name:'Boeing 717-200',maker:'Boeing',code:'B712',engines:2,type:'regional jet',clue:'Developed from the MD-95 and fitted with rear-mounted engines.',d:'hard'},
    {name:'Airbus A340-600',maker:'Airbus',code:'A346',engines:4,type:'wide-body jet',clue:'A very long four-engine Airbus with a centre landing-gear bogie.',d:'hard'}
  ],
  airports: [
    {name:'Hamad International Airport',city:'Doha',country:'Qatar',iata:'DOH',icao:'OTHH',runways:2,hubFor:'Qatar Airways',d:'easy'},
    {name:'Melbourne Airport',city:'Melbourne',country:'Australia',iata:'MEL',icao:'YMML',runways:2,hubFor:'Jetstar and Virgin Australia operations',d:'easy'},
    {name:'Adelaide Airport',city:'Adelaide',country:'Australia',iata:'ADL',icao:'YPAD',runways:2,hubFor:'South Australia’s main airport',d:'easy'},
    {name:'Sydney Airport',city:'Sydney',country:'Australia',iata:'SYD',icao:'YSSY',runways:3,hubFor:'Qantas',d:'easy'},
    {name:'Auckland Airport',city:'Auckland',country:'New Zealand',iata:'AKL',icao:'NZAA',runways:1,hubFor:'Air New Zealand',d:'easy'},
    {name:'Dubai International Airport',city:'Dubai',country:'United Arab Emirates',iata:'DXB',icao:'OMDB',runways:2,hubFor:'Emirates',d:'easy'},
    {name:'Singapore Changi Airport',city:'Singapore',country:'Singapore',iata:'SIN',icao:'WSSS',runways:3,hubFor:'Singapore Airlines',d:'easy'},
    {name:'London Heathrow Airport',city:'London',country:'United Kingdom',iata:'LHR',icao:'EGLL',runways:2,hubFor:'British Airways',d:'easy'},
    {name:'Los Angeles International Airport',city:'Los Angeles',country:'United States',iata:'LAX',icao:'KLAX',runways:4,hubFor:'Major US international gateway',d:'medium'},
    {name:'Tokyo Haneda Airport',city:'Tokyo',country:'Japan',iata:'HND',icao:'RJTT',runways:4,hubFor:'Japan Airlines and ANA',d:'medium'},
    {name:'Seoul Incheon International Airport',city:'Seoul',country:'South Korea',iata:'ICN',icao:'RKSI',runways:4,hubFor:'Korean Air',d:'medium'},
    {name:'Hong Kong International Airport',city:'Hong Kong',country:'Hong Kong',iata:'HKG',icao:'VHHH',runways:3,hubFor:'Cathay Pacific',d:'medium'},
    {name:'Frankfurt Airport',city:'Frankfurt',country:'Germany',iata:'FRA',icao:'EDDF',runways:4,hubFor:'Lufthansa',d:'medium'},
    {name:'Paris Charles de Gaulle Airport',city:'Paris',country:'France',iata:'CDG',icao:'LFPG',runways:4,hubFor:'Air France',d:'medium'},
    {name:'Amsterdam Airport Schiphol',city:'Amsterdam',country:'Netherlands',iata:'AMS',icao:'EHAM',runways:6,hubFor:'KLM',d:'medium'},
    {name:'Kuala Lumpur International Airport',city:'Kuala Lumpur',country:'Malaysia',iata:'KUL',icao:'WMKK',runways:3,hubFor:'Malaysia Airlines',d:'medium'},
    {name:'Nadi International Airport',city:'Nadi',country:'Fiji',iata:'NAN',icao:'NFFN',runways:2,hubFor:'Fiji Airways',d:'hard'},
    {name:'Princess Juliana International Airport',city:'Philipsburg area',country:'Sint Maarten',iata:'SXM',icao:'TNCM',runways:1,hubFor:'Famous Maho Beach approach',d:'hard'},
    {name:'Paro International Airport',city:'Paro',country:'Bhutan',iata:'PBH',icao:'VQPR',runways:1,hubFor:'Mountain-valley approaches',d:'hard'},
    {name:'Lukla Airport',city:'Lukla',country:'Nepal',iata:'LUA',icao:'VNLK',runways:1,hubFor:'Gateway to the Everest region',d:'hard'},
    {name:'Port Moresby Jacksons International Airport',city:'Port Moresby',country:'Papua New Guinea',iata:'POM',icao:'AYPY',runways:2,hubFor:'Air Niugini',d:'hard'},
    {name:'Nouméa La Tontouta International Airport',city:'Nouméa',country:'New Caledonia',iata:'NOU',icao:'NWWW',runways:1,hubFor:'Aircalin',d:'hard'}
  ],
  knowledge: [
    {id:'metar',text:'What does a METAR primarily report?',correct:'Observed aerodrome weather',options:['Observed aerodrome weather','A long-range route plan','An aircraft maintenance defect','Passenger load information'],hint:'It describes conditions that have been observed, not a forecast.',d:'easy'},
    {id:'taf',text:'What is a TAF used for?',correct:'Aerodrome weather forecasting',options:['Aerodrome weather forecasting','Aircraft registration allocation','Airline ticket pricing','Runway pavement inspection'],hint:'The final letter stands for “forecast”.',d:'easy'},
    {id:'squawk7700',text:'Which transponder code generally indicates a general emergency?',correct:'7700',options:['7700','7600','7500','7000'],hint:'It is the emergency code with two sevens followed by two zeros.',d:'easy'},
    {id:'squawk7600',text:'Which transponder code generally indicates radio communication failure?',correct:'7600',options:['7600','7700','7500','2000'],hint:'Think of the emergency codes: 75, 76 and 77.',d:'medium'},
    {id:'squawk7500',text:'Which transponder code generally indicates unlawful interference?',correct:'7500',options:['7500','7600','7700','1200'],hint:'It is the lowest of the three well-known emergency codes.',d:'medium'},
    {id:'iata-airline',text:'How many characters are normally in an IATA airline designator?',correct:'Two',options:['Two','Three','Four','Five'],hint:'Qatar Airways uses QR.',d:'easy'},
    {id:'icao-airline',text:'How many letters are normally in an ICAO airline designator?',correct:'Three',options:['Three','Two','Four','Five'],hint:'Qatar Airways uses QTR.',d:'easy'},
    {id:'icao-airport',text:'How many letters are in a standard ICAO airport location indicator?',correct:'Four',options:['Four','Three','Two','Five'],hint:'Melbourne is YMML.',d:'easy'},
    {id:'nautical-mile',text:'How many metres are in one international nautical mile?',correct:'1,852 metres',options:['1,852 metres','1,609 metres','1,000 metres','2,000 metres'],hint:'It is longer than a statute mile of roughly 1,609 metres.',d:'medium'},
    {id:'knot',text:'A speed of one knot means one what per hour?',correct:'Nautical mile',options:['Nautical mile','Statute mile','Kilometre','Metre'],hint:'The same distance unit commonly used in marine navigation.',d:'easy'},
    {id:'etops',text:'ETOPS rules are most closely associated with which aircraft operations?',correct:'Long-range twin-engine operations',options:['Long-range twin-engine operations','Helicopter hover operations','Glider competitions','Airport ground vehicles'],hint:'The “T” points toward twin-engine aircraft.',d:'medium'},
    {id:'widebody',text:'What usually distinguishes a wide-body passenger airliner cabin?',correct:'Two passenger aisles',options:['Two passenger aisles','A single pilot cockpit','No overhead lockers','Four flight decks'],hint:'It is also commonly called a twin-aisle aircraft.',d:'easy'},
    {id:'v1',text:'During a take-off, what does V1 most directly represent?',correct:'The take-off decision speed',options:['The take-off decision speed','The initial cruise speed','The landing flap limit','The minimum taxi speed'],hint:'Beyond this speed, rejecting the take-off may no longer be the safer option.',d:'hard'},
    {id:'vr',text:'What does VR represent during take-off?',correct:'Rotation speed',options:['Rotation speed','Radio failure speed','Reverse-thrust limit','Runway crossing speed'],hint:'The letter R points to the action that raises the aircraft nose.',d:'medium'},
    {id:'flightlevel',text:'A flight level is referenced to which standard pressure setting?',correct:'1013.25 hPa',options:['1013.25 hPa','1000 hPa','1025 hPa','QFE only'],hint:'It is the international standard atmosphere sea-level pressure.',d:'hard'}
  ],
  liveries: [
    {id:'oneworld',text:'An aircraft carries large “oneworld” titles while retaining its operating airline’s tail. What is this?',correct:'oneworld alliance livery',options:['oneworld alliance livery','Retro livery','Manufacturer house colours','Unpainted test aircraft'],hint:'The wording on the fuselage names the alliance.',d:'easy'},
    {id:'star',text:'Which alliance livery normally features a white fuselage with large “STAR ALLIANCE” titles?',correct:'Star Alliance',options:['Star Alliance','SkyTeam','oneworld','No alliance'],hint:'Its symbol is a five-point arrangement formed from triangular shapes.',d:'easy'},
    {id:'skyteam',text:'Which alliance’s special livery commonly uses a metallic-grey fuselage with a dark-blue tail?',correct:'SkyTeam',options:['SkyTeam','oneworld','Star Alliance','No alliance'],hint:'Its logo resembles a flowing ribbon.',d:'medium'},
    {id:'retro',text:'A modern aircraft painted in an airline’s historic colour scheme is wearing what kind of livery?',correct:'Retro livery',options:['Retro livery','Alliance livery','Factory primer','Wet-lease livery'],hint:'It deliberately recreates a look from the airline’s past.',d:'easy'},
    {id:'anniversary',text:'A paint scheme celebrating an airline’s milestone year is best described as what?',correct:'Anniversary livery',options:['Anniversary livery','Cargo conversion','Prototype scheme','Code-share livery'],hint:'It marks a birthday or major number of years.',d:'medium'},
    {id:'special',text:'A one-off scheme promoting a sports team, film or major event is generally called what?',correct:'Promotional special livery',options:['Promotional special livery','Standard fleet livery','Aircraft primer','Navigation marking'],hint:'It advertises something beyond the airline’s normal brand.',d:'medium'}
  ],
  collections: {
    aircraft: [['A7-BAF','Qatar Airways Boeing 777-300ER'],['Boeing 777-300ER','Long-range twin-engine wide-body'],['Airbus A380','Double-deck superjumbo'],['Boeing 787','Dreamliner family'],['Airbus A350','Modern composite wide-body'],['Boeing 747','Queen of the Skies']],
    airlines: [['Qatar Airways','Doha-based oneworld airline'],['Korean Air','South Korean flag carrier'],['Qantas','Australian flag carrier'],['Air New Zealand','New Zealand flag carrier'],['Singapore Airlines','Singapore flag carrier'],['Emirates','Dubai-based long-haul airline']],
    airports: [['Doha Hamad','Home hub of Qatar Airways'],['Melbourne','Victoria’s major international airport'],['Adelaide','South Australia’s main airport'],['Auckland','New Zealand gateway'],['Sydney','Major Australian international gateway'],['Singapore Changi','Major Asian hub']]
  }
};

const logoUrl = iata => `https://images.kiwi.com/airlines/64/${encodeURIComponent(iata)}.png`;
