[build]
  command = "npm run build"
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, max-age=0"
    Content-Type = "application/json"
